name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker build
      run: |
        docker build . --file Dockerfile --tag registry.cn-shanghai.aliyuncs.com/css_public/myprint:latest --tag registry.cn-shanghai.aliyuncs.com/css_public/myprint:${{ github.sha }}
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        docker push registry.cn-shanghai.aliyuncs.com/css_public/myprint:latest & docker push registry.cn-shanghai.aliyuncs.com/css_public/myprint:${{ github.sha }}
